apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: centos8
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.io/centos:8
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source