apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: image-sign-scan-base
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: image-sign-scan-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: image-sign-scan-base:latest
    source:
      type: Binary
      binary: {}
    strategy:
      dockerStrategy:
        buildArgs:
        - name: OCP_VERSION
          value: "4.3"
        from:
          kind: ImageStreamTag
          name: centos8:latest
      type: Docker
    postCommit: {}
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
