apiVersion: imagesigningrequests.cop.redhat.com/v1alpha1
kind: ImageSigningRequest
metadata:
  name: remote-app
spec:
  containerImage:
    kind: ContainerRepository
    name: quay.io/cnuland/hello-openshift:latest
  pullSecret:
    name: quay