apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagescanningrequests.imagescanningrequests.cop.redhat.com
spec:
  group: imagescanningrequests.cop.redhat.com
  names:
    kind: ImageScanningRequest
    listKind: ImageScanningRequestList
    plural: imagescanningrequests
    singular: imagescanningrequest
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ImageScanningRequest is the Schema for the imagescanningrequests
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            imageStreamTag:
              type: string
          required:
          - imageStreamTag
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
            endTime:
              format: date-time
              type: string
            phase:
              type: string
            scanResult:
              properties:
                failedRules:
                  type: integer
                passedRules:
                  type: integer
                totalRules:
                  type: integer
              required:
              - failedRules
              - passedRules
              - totalRules
              type: object
            startTime:
              format: date-time
              type: string
          type: object
      required:
      - metadata
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
