apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: s2i-golang
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: s2i-golang
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: s2i-golang:latest
    source:
      contextDir: "images/s2i-golang"
      git:
        ref: "signing-webinar"
        uri: "https://github.com/jgoldsmith613/image-scanning-signing-service.git"
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubi8:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange