apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: centos
  spec:
    dockerImageRepository: centos
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhel7
  spec:
    dockerImageRepository: registry.access.redhat.com/rhel7/rhel