apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: image-sign-scan-base
  spec:
    lookupPolicy:
      local: true
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: image-sign-scan-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: image-sign-scan-base:latest
    source:
      contextDir: "images/image-sign-scan-base"
      git:
        ref: "signing-webinar"
        uri: "https://github.com/jgoldsmith613/image-scanning-signing-service.git"
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
        - name: OCP_VERSION
          value: "4.3"
        from:
          kind: ImageStreamTag
          name: centos:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
